// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXpWTjDN0Fuj231waNzW8pOKayMMNqZGM',
    appId: '1:240635551604:web:09d9944db5bcb35f405621',
    messagingSenderId: '240635551604',
    projectId: 'alqurancommunity-24a89',
    authDomain: 'alqurancommunity-24a89.firebaseapp.com',
    storageBucket: 'alqurancommunity-24a89.appspot.com',
    measurementId: 'G-3TNRZW8WKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjeZeqQavUz2lgenu_KHV81nfSuegMtY4',
    appId: '1:240635551604:android:cb0e9e821205ab0c405621',
    messagingSenderId: '240635551604',
    projectId: 'alqurancommunity-24a89',
    storageBucket: 'alqurancommunity-24a89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD73Gb5FoROAKw5cqq-dt69JUQGAycCrVE',
    appId: '1:240635551604:ios:064af66a8edb9a81405621',
    messagingSenderId: '240635551604',
    projectId: 'alqurancommunity-24a89',
    storageBucket: 'alqurancommunity-24a89.appspot.com',
    iosClientId: '240635551604-m79icd6rp3e33js1fp00qpjv0o40i2oi.apps.googleusercontent.com',
    iosBundleId: 'com.example.tasbehtest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD73Gb5FoROAKw5cqq-dt69JUQGAycCrVE',
    appId: '1:240635551604:ios:064af66a8edb9a81405621',
    messagingSenderId: '240635551604',
    projectId: 'alqurancommunity-24a89',
    storageBucket: 'alqurancommunity-24a89.appspot.com',
    iosClientId: '240635551604-m79icd6rp3e33js1fp00qpjv0o40i2oi.apps.googleusercontent.com',
    iosBundleId: 'com.example.tasbehtest',
  );
}
